image: alpine

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_REF_PROTECTED

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - docs
  - publish

before_script:
  - apk update
  - "apk add build-base linux-headers make cmake git bash \
    zlib-dev openssl-libs-static openssl-dev openssl \
    doxygen ttf-freefont graphviz"

build:mud:
  stage: build
  script:
    - make -j install # build and install (copies web files to bin/www/ and libs to build/)
  artifacts:
    paths:
      - bin
      - build

publish:dev-docs:
  stage: docs
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
      - documentation/html
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish:client:
  stage: build
  script:
    - cp -r bin/www/ client-pages
  artifacts:
    paths:
      - client-pages
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: publish
  dependencies:
    - publish:dev-docs
    - publish:client
  script:
    - cp -r homepage public
    - cp -r documentation/html public/dev-docs
    - cp -r client-pages public/client
  artifacts:
    paths:
      - public
  rules: # publish only on default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
