image: alpine

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_REF_PROTECTED

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - release
  - docs
  - publish
  - kanban

.build-deps: &build-deps
  - apk update
  - apk add build-base linux-headers make git
    zlib-dev zlib-static rsync xz

before_script:
  - *build-deps
  - apk add bash doxygen ttf-freefont graphviz expect busybox-extras xz

build:mud:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - make -j install # build and install (copies web files to bin/www/ and libs to build/)
  artifacts:
    paths:
      - bin
      - build

test:unit:
  stage: test
  dependencies:
    - build:mud
  script:
    - make tests
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test:smoke:
  stage: test
  dependencies:
    - build:mud
  script:
    - make smoke
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test:valgrind:
  stage: test
  before_script:
    - *build-deps
    - apk add valgrind
  dependencies:
    - build:mud
  script:
    - make run-tests-valgrind
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

release:source:
  stage: release
  before_script:
    - apk update
    - apk add git xz
  script:
    - ./scripts/release-tar
  artifacts:
    paths:
      - boris-*.tar.xz
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

release:linux-x86_64:
  stage: release
  before_script:
    - *build-deps
  script:
    - make distclean || true
    - make -j LDFLAGS="-static" install
    - ./scripts/build-release linux-x86_64
  artifacts:
    paths:
      - boris-*-linux-x86_64.tar.xz
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish:dev-docs:
  stage: docs
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
      - documentation/html
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish:client:
  stage: docs
  dependencies:
    - build:mud
  script:
    - cp -r bin/www/ client-pages
  artifacts:
    paths:
      - client-pages
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish:docs:
  stage: docs
  before_script:
    - apk update
    - apk add pandoc
  script:
    - ./scripts/pages-build.sh doc-pages
  artifacts:
    paths:
      - doc-pages
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: publish
  dependencies:
    - publish:dev-docs
    - publish:client
    - publish:docs
  script:
    - cp -r homepage public
    - cp -r documentation/html public/dev-docs
    - cp -r client-pages public/client
    - cp -r doc-pages public/docs
  artifacts:
    paths:
      - public
  rules: # publish only on default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

sync:kanban:
  stage: kanban
  image: alpine
  before_script:
    - apk update
    - apk add curl git sed
  script:
    - ./scripts/kanban-sync.sh
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - kanban/*.md
        - scripts/kanban-sync.sh
