image: alpine

before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz

##DISABLED
# preview-docs:
#  script:
#    - doxygen Doxyfile
#  rules:
#    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

publish-docs:
  script:
    - doxygen Doxyfile
    - mv documentation/html public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
