image: alpine

stages:
  build
  publish

before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz
  - apk add build-base cmake bash

publish:dev-docs:
  stage: build
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
      - documentation/html
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish:client:
  stage: build
  script:
    - make WEB_INSTALL_DIR="client-pages" install
  artifacts:
    paths:
      - client-pages
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish:pages:
  stage: publish
  dependencies:
    - publish:dev-docs
    - public:client
  script:
    # TODO: - cp -r homepage public
    - mkdir -p public
    - cp -r documentation/html public/dev-docs
    - cp -r client-pages public/client
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
