image: alpine

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - docs
  - publish

before_script:
  - apk update
  - "apk add build-base linux-headers make cmake git bash \
    zlib-dev openssl-libs-static openssl-dev openssl \
    doxygen ttf-freefont graphviz"

build:mud:
  stage: build
  script:
    - make -j
  artifacts:
    paths:
      - bin
      - build

publish:dev-docs:
  stage: docs
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
      - documentation/html
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish:client:
  stage: build
  script:
    - cp -r src/web/client/ client-pages/
    - mv client-pages/assets/default/* client-pages/assets/
    - rm -rf client-pages/assets/default/
  artifacts:
    paths:
      - client-pages
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: publish
  dependencies:
    - publish:dev-docs
    - publish:client
  script:
    - cp -r homepage public
    - cp -r documentation/html public/dev-docs
    - cp -r client-pages public/client
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
