image: alpine

before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz

test:
  script:
    - doxygen Doxyfile
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - doxygen Doxyfile
    - mv documentation/html public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
