language: c
dist: xenial
addons:
  apt:
    packages:
      - libtelnet-dev
      - libevent-dev
      - libssh-dev
      - libmicrohttpd-dev
      - liblmdb-dev
script:
  - make all
  - make clean-all
